repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: ruff-format
        name: Format with ruff
        entry: uvx ruff format
        language: system
        types: [python]
        
      - id: ruff-check
        name: Check with ruff
        entry: uvx ruff check --fix
        language: system
        types: [python]
        
      - id: mypy
        name: Type check with mypy
        entry: uv run mypy src/app
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
